### ISSUE TITLE
Transient with non-equidistant time spacing

### ISSUE THREAD

**Issue by chrlein** [nocliper/ilt#2]
Hi Anton,
awesome tool, thanks for sharing! 
I was wondering if it's also possible to import data containing time steps? Our DLTS setup doesn't sample the capacitance transient equidistant, so its not possible to use the "t_step". Is it already possible to include it in the .DLTS file or would the "read_file.py" module need a change?

Many thanks for you help,
Chris

**Comment by nocliper** [comment]
Hi Chris, I'm glad you found it useful! 
Regarding your question, it is possible and it should be easily implemented by just modifying `read_file.py` to include your time points in the `time` array. By the way, exponential spaced transients should work even better with this code, but I haven't tested it with non-equidistant data. You should verify the results with synthetic data.

The above will work if every transient has the same time points. If not, you will need to make some modifications in `demo.py` and `hp.py` modules to compute and save data with respect to each transient's time points.
